### ISSUE TITLE
Feature Request: Add alternative methods for calculating implied odds

### ISSUE THREAD

**Issue by carlzoo** [ian-shepherd/pybettor#1]
Thanks for working on this Python library - I was trying to make something similar myself. 

The method used for the implied odds is using the basic (multiplicative) method which is the least method. There should be other methods similar to those in the R implied odds library:

https://cran.r-project.org/web/packages/implied/vignettes/introduction.html

**Comment by ian-shepherd** [comment]
We will add this to our next sprint along with replicating clv_calc, clv_hfa, edge_calc, hold_calc from our R [library](https://github.com/a-i-sports/bettoR/tree/master/R). We are working through adding all these functions but don't have a specific order we need to go in. If there are functions you want us to prioritize or add from your other work you mentioned please let us know and we are happy to incorporate that.

**Comment by ian-shepherd** [comment]
Jason is going to review as well, but feel free to look yourself. There are some very slight differences between our output and the R library at 6 decimal places out. I believe it is down to methods that use optimizer and how the different libraries compute the value.
